let arrofobj=
{
    arr1:["JavaScript","Python","Ruby","Go","languages","isChallenging","isRewarding","difficulty","isFun"],
    arr2:["JavaScript","Python","Ruby","Go"],
    arr3:[true,true,7,true],
    show()
    {
        this.arr1.forEach(function(item)
        {
            console.log(item);
        }),
        console.log(this.arr2),
        this.arr3.forEach(function(item)
        {
            console.log(item)
        })
    }
}
arrofobj.show()